In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.4


In [ ]:
#array
#if array has single paranthesis then it is an 1D array

a = np.array([1,2,3,4,5])
#ndim it is used to know which dimensional array is being used
a.ndim

1

In [29]:
#2D array
d = np.array([[11,12,13]])
d.ndim



2

In [30]:
#3D array
b = np.array([[[1,2],[45,67]]])
b.ndim

3

In [39]:
#arange
#syntax- arange(start,stop,stepsize)
s = np.arange(0,25)
s


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
len(s)

25

In [41]:
# r,c r=index,c=coloumn

#shape = it will identify the dimensionality of the r,c
s.shape


(25,)

In [114]:
#reshape = it brings to the shape according to your desire nothing but r,c
# better to take another variable to store reshape function
m = s.reshape(5,5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
m.shape

(5, 5)

In [50]:
#print 100 numbers

d = np.arange(0,100)
q = d.reshape(10,10)
q

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [51]:
q.shape

(10, 10)

In [68]:
t = np.arange(0,19)
t.reshape(1,19)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18]])

In [73]:
# IDENTITY MATRIX- PRINCIPAL DIAGNOL VALUE IS 1 AND REMAINING ELEMENTS ARE 0
aa = np.identity(5)
aa

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [89]:
aa = np.eye(5)*5
aa 

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [79]:
aa = np.zeros(5)
aa

array([0., 0., 0., 0., 0.])

In [112]:
#create 2 matrices with size 4x4
bb = np.arange(0,16)
dd = np.arange(17,33)
l = bb.reshape(4,4)
l


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
q = dd.reshape(4,4)
q

array([[17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [113]:
cc = l*q
cc

array([[  0,  18,  38,  60],
       [ 84, 110, 138, 168],
       [200, 234, 270, 308],
       [348, 390, 434, 480]])

In [ ]:
#PANDAS- it is used to frame the data
import numpy as np
import pandas as pd


In [117]:
a = np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
#Data frame syntax
#variable = pd.DataFrame(data,index = index,columns = columns)
f = pd.DataFrame(data = a, index = ['row1','row2','row3','row4'], columns = ['temp','rain','humidity','wind'])
f

temp  rain  humidity  wind
row1     0     1         2     3
row2     4     5         6     7
row3     8     9        10    11
row4    12    13        14    15

In [120]:
# how to convert into csv file

f.to_csv('rainfall.csv')

In [3]:
#read csv is used to read the exported file or the file which is already in the folder
import pandas as pd
mm = pd.read_csv('EAFC26-Men.csv')
mm

ID   Rank                   Name GENDER  OVR  PAC  SHO  PAS  DRI  \
0      209331      1          Mohamed Salah      M   91   89   88   86   90   
1      231747      3          Kylian Mbappé      M   91   97   90   81   92   
2      231443      5        Ousmane Dembélé      M   90   91   88   83   93   
3      231866      6                  Rodri      M   90   65   80   86   84   
4      203376      8        Virgil van Dijk      M   90   73   60   72   72   
...       ...    ...                    ...    ...  ...  ...  ...  ...  ...   
16223   70654  17869  Aaron Vanlalrinchhana      M   47   47   48   44   50   
16224  275674  17870               Ma Haoqi      M   47   50   48   42   50   
16225   76506  17871             Yu Zhuowei      M   47   57   46   37   46   
16226  275659  17872              He Bizhen      M   47   60   23   29   31   
16227  272761  17873           Lyu Jiaqiang      M   47   56   26   28   33   

       DEF  ...              League              Team  \
0       45  ...      Premier League         Liverpool   
1       37  ...    LALIGA EA SPORTS       Real Madrid   
2       50  ...  Ligue 1 McDonald's          Paris SG   
3       86  ...      Premier League   Manchester City   
4       90  ...      Premier League         Liverpool   
...    ...  ...                 ...               ...   
16223   23  ...                 ISL      Hyderabad FC   
16224   22  ...                 CSL      Zhejiang Pro   
16225   16  ...                 CSL     Dalian Yingbo   
16226   50  ...                 CSL  Shanghai Shenhua   
16227   50  ...                 CSL    Tianjin JMT FC   

                                              play style  \
0      ['Finesse Shot+', 'First Touch', 'Gamechanger'...   
1      ['Quick Step+', 'Acrobatic', 'Finesse Shot', '...   
2      ['Rapid+', 'Inventive', 'Low Driven Shot', 'Pi...   
3      ['Tiki Taka+', 'Aerial Fortress', 'Bruiser', '...   
4      ['Intercept+', 'Aerial Fortress', 'Anticipate'...   
...                                                  ...   
16223                                                 []   
16224                                                 []   
16225                                                 []   
16226                                                 []   
16227                                                 []   

                                                     url  GK Diving  \
0      https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
1      https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
2      https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
3      https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
4      https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
...                                                  ...        ...   
16223  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16224  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16225  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16226  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16227  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   

       GK Handling  GK Kicking  GK Positioning  GK Reflexes  \
0              NaN         NaN             NaN          NaN   
1              NaN         NaN             NaN          NaN   
2              NaN         NaN             NaN          NaN   
3              NaN         NaN             NaN          NaN   
4              NaN         NaN             NaN          NaN   
...            ...         ...             ...          ...   
16223          NaN         NaN             NaN          NaN   
16224          NaN         NaN             NaN          NaN   
16225          NaN         NaN             NaN          NaN   
16226          NaN         NaN             NaN          NaN   
16227          NaN         NaN             NaN          NaN   

                                              

In [4]:
# shape to know the dimensions 
mm.shape

(16228, 59)

In [14]:
# How to find the missing values of the dataset
mm.isnull().sum()

ID                           0
Rank                         0
Name                         0
GENDER                       0
OVR                          0
PAC                          0
SHO                          0
PAS                          0
DRI                          0
DEF                          0
PHY                          0
Acceleration                 0
Sprint Speed                 0
Positioning                  0
Finishing                    0
Shot Power                   0
Long Shots                   0
Volleys                      0
Penalties                    0
Vision                       0
Crossing                     0
Free Kick Accuracy           0
Short Passing                0
Long Passing                 0
Curve                        0
Dribbling                    0
Agility                      0
Balance                      0
Reactions                    0
Ball Control                 0
Composure                    0
Interceptions                0
Heading 

In [6]:
# describe
# which will give the calculation of mean median mode standard deviation
# this mathematical calc is only done for the integers values in the datasets
mm.describe()

ID          Rank           OVR           PAC           SHO  \
count   16228.000000  16228.000000  16228.000000  16228.000000  16228.000000   
mean   215646.635322   9360.295415     66.241126     68.151836     54.346069   
std     68202.909896   5050.951462      6.823219     10.435775     13.717709   
min     19541.000000      1.000000     47.000000     30.000000     21.000000   
25%    209219.750000   5119.750000     62.000000     62.000000     45.000000   
50%    241153.500000   9510.500000     66.000000     69.000000     57.000000   
75%    261788.000000  13707.250000     70.000000     75.000000     64.000000   
max    279948.000000  17873.000000     91.000000     97.000000     92.000000   

                PAS           DRI           DEF          PHY  Acceleration  \
count  16228.000000  16228.000000  16228.000000  16228.00000  16228.000000   
mean      58.602662     63.659354     50.563902     65.21124     64.666687   
std        9.615111      9.126835     16.533785      9.46065     15.465171   
min       25.000000     29.000000     15.000000     32.00000     15.000000   
25%       52.000000     58.000000     36.000000     59.00000     57.000000   
50%       59.000000     64.000000     55.000000     66.00000     68.000000   
75%       65.000000     70.000000     64.000000     72.00000     75.000000   
max       92.000000     93.000000     90.000000     91.00000     97.000000   

       ...      Strength    Aggression     Weak foot   Skill moves  \
count  ...  16228.000000  16228.000000  16228.000000  16228.000000   
mean   ...     65.319509     56.353340      2.943493      2.375770   
std    ...     12.234758     16.636886      0.669765      0.774531   
min    ...     25.000000     11.000000      1.000000      1.000000   
25%    ...     58.000000     47.000000      3.000000      2.000000   
50%    ...     66.000000     60.000000      3.000000      2.000000   
75%    ...     74.000000     68.000000      3.000000      3.000000   
max    ...     95.000000     94.000000      5.000000      5.000000   

                Age    GK Diving  GK Handling   GK Kicking  GK Positioning  \
count  16228.000000  1816.000000  1816.000000  1816.000000     1816.000000   
mean      25.854449    65.078744    63.213106    62.340308       63.648678   
std        4.690417     7.457566     7.186018     7.439071        8.016507   
min       17.000000    45.000000    45.000000    45.000000       41.000000   
25%       22.000000    60.000000    58.000000    57.000000       58.000000   
50%       25.000000    65.000000    63.000000    62.000000       64.000000   
75%       29.000000    70.000000    68.000000    67.000000       69.000000   
max       44.000000    90.000000    90.000000    91.000000       90.000000   

       GK Reflexes  
count  1816.000000  
mean     65.838106  
std       7.889122  
min      45.000000  
25%      60.000000  
50%      66.000000  
75%      71.000000  
max      90.000000  

[8 rows x 46 columns]

In [5]:
# HEAD 
# if you want to read only first five rows and columns
mm.head()

ID  Rank             Name GENDER  OVR  PAC  SHO  PAS  DRI  DEF  ...  \
0  209331     1    Mohamed Salah      M   91   89   88   86   90   45  ...   
1  231747     3    Kylian Mbappé      M   91   97   90   81   92   37  ...   
2  231443     5  Ousmane Dembélé      M   90   91   88   83   93   50  ...   
3  231866     6            Rodri      M   90   65   80   86   84   86  ...   
4  203376     8  Virgil van Dijk      M   90   73   60   72   72   90  ...   

               League             Team  \
0      Premier League        Liverpool   
1    LALIGA EA SPORTS      Real Madrid   
2  Ligue 1 McDonald's         Paris SG   
3      Premier League  Manchester City   
4      Premier League        Liverpool   

                                          play style  \
0  ['Finesse Shot+', 'First Touch', 'Gamechanger'...   
1  ['Quick Step+', 'Acrobatic', 'Finesse Shot', '...   
2  ['Rapid+', 'Inventive', 'Low Driven Shot', 'Pi...   
3  ['Tiki Taka+', 'Aerial Fortress', 'Bruiser', '...   
4  ['Intercept+', 'Aerial Fortress', 'Anticipate'...   

                                                 url  GK Diving  GK Handling  \
0  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
1  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
2  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
3  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
4  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   

   GK Kicking  GK Positioning  GK Reflexes  \
0         NaN             NaN          NaN   
1         NaN             NaN          NaN   
2         NaN             NaN          NaN   
3         NaN             NaN          NaN   
4         NaN             NaN          NaN   

                                                card  
0  https://ratings-images-prod.pulse.ea.com/FC26/...  
1  https://ratings-images-prod.pulse.ea.com/FC26/...  
2  https://ratings-images-prod.pulse.ea.com/FC26/...  
3  https://ratings-images-prod.pulse.ea.com/FC26/...  
4  https://ratings-images-prod.pulse.ea.com/FC26/...  

[5 rows x 59 columns]

In [8]:
# if want specific number of rows then add an argument in the head() function
mm.head(8)

ID  Rank             Name GENDER  OVR  PAC  SHO  PAS  DRI  DEF  ...  \
0  209331     1    Mohamed Salah      M   91   89   88   86   90   45  ...   
1  231747     3    Kylian Mbappé      M   91   97   90   81   92   37  ...   
2  231443     5  Ousmane Dembélé      M   90   91   88   83   93   50  ...   
3  231866     6            Rodri      M   90   65   80   86   84   86  ...   
4  203376     8  Virgil van Dijk      M   90   73   60   72   72   90  ...   
5  252371     9  Jude Bellingham      M   90   80   86   83   90   78  ...   
6  239085    10   Erling Haaland      M   90   86   91   70   80   45  ...   
7  233419    11         Raphinha      M   89   91   84   85   87   53  ...   

               League             Team  \
0      Premier League        Liverpool   
1    LALIGA EA SPORTS      Real Madrid   
2  Ligue 1 McDonald's         Paris SG   
3      Premier League  Manchester City   
4      Premier League        Liverpool   
5    LALIGA EA SPORTS      Real Madrid   
6      Premier League  Manchester City   
7    LALIGA EA SPORTS     FC Barcelona   

                                          play style  \
0  ['Finesse Shot+', 'First Touch', 'Gamechanger'...   
1  ['Quick Step+', 'Acrobatic', 'Finesse Shot', '...   
2  ['Rapid+', 'Inventive', 'Low Driven Shot', 'Pi...   
3  ['Tiki Taka+', 'Aerial Fortress', 'Bruiser', '...   
4  ['Intercept+', 'Aerial Fortress', 'Anticipate'...   
5  ['Relentless+', 'First Touch', 'Gamechanger', ...   
6  ['Low Driven Shot+', 'Acrobatic', 'Chip Shot',...   
7  ['Rapid+', 'Finesse Shot', 'Power Shot', 'Quic...   

                                                 url  GK Diving  GK Handling  \
0  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
1  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
2  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
3  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
4  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
5  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
6  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   
7  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN          NaN   

   GK Kicking  GK Positioning  GK Reflexes  \
0         NaN             NaN          NaN   
1         NaN             NaN          NaN   
2         NaN             NaN          NaN   
3         NaN             NaN          NaN   
4         NaN             NaN          NaN   
5         NaN             NaN          NaN   
6         NaN             NaN          NaN   
7         NaN             NaN          NaN   

                                                card  
0  https://ratings-images-prod.pulse.ea.com/FC26/...  
1  https://ratings-images-prod.pulse.ea.com/FC26/...  
2  https://ratings-images-prod.pulse.ea.com/FC26/...  
3  https://ratings-images-prod.pulse.ea.com/FC26/...  
4  https://ratings-images-prod.pulse.ea.com/FC26/...  
5  https://ratings-images-prod.pulse.ea.com/FC26/...  
6  https://ratings-images-prod.pulse.ea.com/FC26/...  
7  https://ratings-images-prod.pulse.ea.com/FC26/...  

[8 rows x 59 columns]

In [9]:
#tail
#gives bottom 5 rows of the data set
mm.tail()

ID   Rank                   Name GENDER  OVR  PAC  SHO  PAS  DRI  \
16223   70654  17869  Aaron Vanlalrinchhana      M   47   47   48   44   50   
16224  275674  17870               Ma Haoqi      M   47   50   48   42   50   
16225   76506  17871             Yu Zhuowei      M   47   57   46   37   46   
16226  275659  17872              He Bizhen      M   47   60   23   29   31   
16227  272761  17873           Lyu Jiaqiang      M   47   56   26   28   33   

       DEF  ...  League              Team  play style  \
16223   23  ...     ISL      Hyderabad FC          []   
16224   22  ...     CSL      Zhejiang Pro          []   
16225   16  ...     CSL     Dalian Yingbo          []   
16226   50  ...     CSL  Shanghai Shenhua          []   
16227   50  ...     CSL    Tianjin JMT FC          []   

                                                     url  GK Diving  \
16223  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16224  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16225  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16226  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16227  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   

       GK Handling  GK Kicking  GK Positioning  GK Reflexes  \
16223          NaN         NaN             NaN          NaN   
16224          NaN         NaN             NaN          NaN   
16225          NaN         NaN             NaN          NaN   
16226          NaN         NaN             NaN          NaN   
16227          NaN         NaN             NaN          NaN   

                                                    card  
16223  https://ratings-images-prod.pulse.ea.com/FC26/...  
16224  https://ratings-images-prod.pulse.ea.com/FC26/...  
16225  https://ratings-images-prod.pulse.ea.com/FC26/...  
16226  https://ratings-images-prod.pulse.ea.com/FC26/...  
16227  https://ratings-images-prod.pulse.ea.com/FC26/...  

[5 rows x 59 columns]

In [ ]:
# if want specific number of rows then pass the argument in the tail function 
mm.tail(7)

ID   Rank                   Name GENDER  OVR  PAC  SHO  PAS  DRI  \
16221   77200  17867            Kim Ji Woon      M   47   63   29   33   41   
16222   71329  17868          Kim Chang Hun      M   47   57   45   40   53   
16223   70654  17869  Aaron Vanlalrinchhana      M   47   47   48   44   50   
16224  275674  17870               Ma Haoqi      M   47   50   48   42   50   
16225   76506  17871             Yu Zhuowei      M   47   57   46   37   46   
16226  275659  17872              He Bizhen      M   47   60   23   29   31   
16227  272761  17873           Lyu Jiaqiang      M   47   56   26   28   33   

       DEF  ...      League              Team  play style  \
16221   42  ...  K League 1       Jeju United          []   
16222   21  ...  K League 1   Jeonbuk Hyundai          []   
16223   23  ...         ISL      Hyderabad FC          []   
16224   22  ...         CSL      Zhejiang Pro          []   
16225   16  ...         CSL     Dalian Yingbo          []   
16226   50  ...         CSL  Shanghai Shenhua          []   
16227   50  ...         CSL    Tianjin JMT FC          []   

                                                     url  GK Diving  \
16221  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16222  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16223  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16224  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16225  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16226  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   
16227  https://www.ea.com/games/ea-sports-fc/ratings/...        NaN   

       GK Handling  GK Kicking  GK Positioning  GK Reflexes  \
16221          NaN         NaN             NaN          NaN   
16222          NaN         NaN             NaN          NaN   
16223          NaN         NaN             NaN          NaN   
16224          NaN         NaN             NaN          NaN   
16225          NaN         NaN             NaN          NaN   
16226          NaN         NaN             NaN          NaN   
16227          NaN         NaN             NaN          NaN   

                                                    card  
16221  https://ratings-images-prod.pulse.ea.com/FC26/...  
16222  https://ratings-images-prod.pulse.ea.com/FC26/...  
16223  https://ratings-images-prod.pulse.ea.com/FC26/...  
16224  https://ratings-images-prod.pulse.ea.com/FC26/...  
16225  https://ratings-images-prod.pulse.ea.com/FC26/...  
16226  https://ratings-images-prod.pulse.ea.com/FC26/...  
16227  https://ratings-images-prod.pulse.ea.com/FC26/...  

[7 rows x 59 columns]

In [12]:
# Filling the null values 


In [ ]:
aa=pd.read_csv('rehan.csv')

aa

Unnamed: 0  temp  rain  humidity  wind
0       row1   0.0   1.0       NaN     3
1       row2   4.0   5.0       6.0     7
2       row3   8.0   NaN       NaN    11
3       row4   NaN  13.0      14.0    15

In [ ]:
# it gives all the missing values in the dataset
aa.isnull().sum()


Unnamed: 0    0
temp          1
rain          1
humidity      2
wind          0
dtype: int64

In [ ]:
#fillna() is used to fill the missing values manually
# inplace = True
# it will overwrite the data set
aa.fillna(3,inplace=True)
aa

Unnamed: 0  temp  rain  humidity  wind
0       row1   0.0   1.0       3.0     3
1       row2   4.0   5.0       6.0     7
2       row3   8.0   3.0       3.0    11
3       row4   3.0  13.0      14.0    15